export const SUBJECTS = [
  {
    id: 1,
    name: "Physics",
    code: "PHY",
    accent: "from-sky-500 to-blue-700",
    chapters: [
      "Fibre Optics",
      "Quantum Mechanics",
      "Interference and Diffraction",
      "Sensors",
      "Lasers",
      "Electrodynamics",
    ],
    playlists: {
      1: "PLgwJf8NK-2e4d2AyXC7pvXtgJ51qz-HWV",
      2: "PL81b_GzVmpj9NFwavO_SpM8uSFfpbUPLP",
      3: "PLnU_6InKwomHnK2BzUmB1GD4LEG4dAAUS",
      4: "PLm5sdXlz-wPmbrgB5XQJWufmS0ffMtFTp",
      5: "PL81b_GzVmpj8ECOVlzS4ov-FC1j-YHdMC",
      6: "PLm5sdXlz-wPnF73Q-AAnC8FtO92Jpc9JA",
    },
    descriptions: {
      0: "We are going to learn about Physics. Physics is the branch of science concerned with the nature and properties of matter and energy. It encompasses a wide range of phenomena, from the smallest subatomic particles to the largest galaxies. In this course, we will explore various topics in physics, including mechanics, electromagnetism, thermodynamics, quantum mechanics, and more. Through lectures, demonstrations, and problem-solving sessions, we aim to develop a deep understanding of the fundamental principles that govern the physical world around us.",
      1: "This lecture covers the fundamentals of optical fibres, including their structure, working principle, and applications. It also delves into the concept of numerical aperture, which is crucial for understanding light propagation in fibres. The lecture includes problem-solving sessions on numerical aperture, acceptance angle, V-number, modes of propagation, and the differences between step index and graded index fibres. By the end of this lecture, students will have a solid understanding of optical fibres and their significance in modern communication systems.",
      2: "This lecture provides an introduction to quantum mechanics, covering key concepts such as wave-particle duality, the uncertainty principle, and the time-dependent and time-independent Schrödinger equations. It also explores phase and group velocity, which are essential for understanding wave propagation in quantum systems. The lecture includes numerical problems to reinforce the theoretical concepts and enhance problem-solving skills in quantum mechanics.",
      3: "This lecture explores the phenomena of interference and diffraction, which are fundamental to understanding wave behavior. It covers the principles of superposition, constructive and destructive interference, and the conditions for observing interference patterns. The lecture also delves into diffraction, including single-slit and double-slit diffraction, as well as diffraction gratings. By the end of this lecture, students will have a comprehensive understanding of how waves interact and the resulting patterns that emerge.",
      4: "This lecture focuses on sensors, which are devices that detect and respond to changes in the environment. It covers various types of sensors, including temperature sensors, pressure sensors, and optical sensors. The lecture also explores the principles of sensor operation, signal processing, and applications in different fields such as healthcare, automotive, and industrial automation. By the end of this lecture, students will have a solid understanding of sensor technology and its significance in modern society.",
      5: "This lecture provides an overview of lasers, covering their principles of operation, types, and applications. It explores the concept of stimulated emission, population inversion, and the different components of a laser system. The lecture also delves into various types of lasers, including solid-state lasers, gas lasers, and semiconductor lasers. By the end of this lecture, students will have a comprehensive understanding of laser technology and its wide-ranging applications in fields such as medicine, communication, and manufacturing.",
      6: "This lecture covers the fundamentals of electrodynamics, which is the study of electric and magnetic fields and their interactions with charged particles. It explores Maxwell's equations, which describe how electric and magnetic fields are generated and altered by charges and currents. The lecture also delves into electromagnetic waves, their propagation, and applications in communication systems. By the end of this lecture, students will have a solid understanding of electrodynamics and its significance in modern physics and engineering.",
    },
  },
  {
    id: 2,
    name: "Mathematics",
    code: "MATH",
    accent: "from-violet-500 to-purple-700",
    chapters: [
      "Matrices",
      "Complex Numbers, Hyperbolic function and Logarithm of Complex Numbers",
      "Partial Differentiation",
      "Application of Partial Differentiation",
      "Numerical Methods",
      "Beta and Gamma Functions and DUIS",
      "Multiple Integrals",
      "Differential Equations of First Order and First Degree",
      "Higher Order Linear Differential Equations with Constant Coefficients and Variable Coefficients",
    ],
    playlists: {
      1: "PL81b_GzVmpj974icYMeETH4DWa4MpU7ZH",
      2: "PLKS7ZMKnbPrSsOQDQOpYrDUp-4zQO8YFX",
      3: "PLT3bOBUU3L9iRoyhs8V1Io-xEsjfq4zI0",
      4: "PL81b_GzVmpj9FatpGbvAzosSGgOAAn5uA",
      5: "PLT3bOBUU3L9i9Ysvmznuawv1mR1r6ml0R",
      6: "PLELyD9hiZ4kjTqFvhtfb0tkSS8pdopqvx",
      7: "PLMBARyqASPojTZP7JXdi8zb5YB0dzmugY",
      8: "PLT3bOBUU3L9g0aergP43HK9ihc_UG7Kbx",
      9: "PLX-8MeNTXgAmKzmCB0zk3Rre68isiVIf5",
    },
    descriptions: {
      0: "Mathematics is a fundamental subject that plays a crucial role in various fields, including science, engineering, economics, and technology. It provides the tools and frameworks necessary for understanding and solving complex problems. The subject encompasses a wide range of topics, from basic arithmetic and algebra to advanced calculus, linear algebra, and differential equations. Mathematics is not only essential for academic pursuits but also for everyday life, as it helps us make informed decisions, analyze data, and understand patterns in the world around us. In this lecture series, we will explore key mathematical concepts and their applications across different disciplines.",
      1: "Matrices are a fundamental mathematical tool used in various fields, including physics, engineering, computer science, and economics. They provide a compact way to represent and manipulate data, solve systems of linear equations, and perform transformations in space. In this lecture, we will explore the basics of matrices, including their properties, operations such as addition, multiplication, and inversion, and their applications in solving real-world problems. We will also delve into concepts like determinants and eigenvalues, which are crucial for understanding the behavior of linear transformations and systems of equations. By the end of this lecture, you will have a solid foundation in matrix theory and its applications.",
      2: "Complex numbers are an extension of the real number system that includes the imaginary unit, denoted as 'i', where i^2 = -1. They are used to represent quantities that cannot be expressed as real numbers, such as the square root of negative numbers. In this lecture, we will explore the properties and operations of complex numbers, including addition, subtraction, multiplication, and division. We will also delve into hyperbolic functions, which are analogs of trigonometric functions but for a hyperbola instead of a circle. Additionally, we will discuss the logarithm of complex numbers and its applications in various fields such as engineering and physics. By the end of this lecture, you will have a comprehensive understanding of complex numbers and their significance in mathematics and beyond.",
      3: "Partial differentiation is a mathematical technique used to analyze functions of multiple variables. It involves taking the derivative of a function with respect to one variable while treating the other variables as constants. This technique is essential in various fields, including physics, engineering, and economics, as it allows us to understand how a function changes with respect to each variable independently. In this lecture, we will explore the concept of partial differentiation, its rules and properties, and its applications in solving problems involving multivariable functions. We will also discuss higher-order partial derivatives and their significance in understanding the curvature and behavior of functions in multiple dimensions. By the end of this lecture, you will have a solid grasp of partial differentiation and its applications in real-world scenarios.",
      4: "Application of partial differentiation is a crucial aspect of multivariable calculus that allows us to analyze and solve real-world problems involving functions of multiple variables. In this lecture, we will explore how partial differentiation can be applied to optimize functions, find critical points, and analyze the behavior of functions in various contexts. We will discuss techniques such as Lagrange multipliers for constrained optimization and how to use partial derivatives to determine the nature of critical points (maxima, minima, or saddle points). Additionally, we will delve into applications in physics, engineering, and economics, where partial differentiation is used to model and solve complex problems. By the end of this lecture, you will have a deeper understanding of how to apply partial differentiation effectively in various scenarios.",
      5: "Numerical methods are a set of techniques used to approximate solutions to mathematical problems that cannot be solved analytically. These methods are essential in various fields, including engineering, physics, and computer science, where complex equations and systems often arise. In this lecture, we will explore different numerical methods for solving equations, such as the Newton-Raphson method, bisection method, and secant method. We will also discuss numerical integration techniques like the trapezoidal rule and Simpson's rule. Additionally, we will delve into the importance of error analysis and convergence in numerical methods to ensure accurate and reliable results. By the end of this lecture, you will have a solid understanding of numerical methods and their applications in solving real-world problems.",
      6: "Beta and Gamma functions are special mathematical functions that play a crucial role in various fields, including probability theory, statistics, and physics. The Beta function is defined as an integral that generalizes the factorial function to non-integer values, while the Gamma function extends the factorial function to complex numbers. In this lecture, we will explore the properties and applications of both functions. We will discuss how the Beta function can be used to compute probabilities in beta distributions and how the Gamma function is essential in defining distributions such as the gamma distribution. Additionally, we will delve into the relationship between these functions and their significance in solving problems involving integrals and series. By the end of this lecture, you will have a comprehensive understanding of Beta and Gamma functions and their applications in various mathematical contexts.",
      7: "Multiple integrals are a fundamental concept in multivariable calculus that allow us to compute volumes, areas, and other quantities in higher dimensions. They extend the idea of single-variable integration to functions of multiple variables. In this lecture, we will explore the concept of double and triple integrals, their properties, and how to evaluate them using various techniques such as iterated integrals and change of variables. We will also discuss applications of multiple integrals in physics, engineering, and probability theory, where they are used to model phenomena such as mass distribution, fluid flow, and probability densities. By the end of this lecture, you will have a solid understanding of multiple integrals and their significance in analyzing functions of several variables.",
      8: "Differential equations of first order and first degree are a fundamental topic in mathematics that have wide-ranging applications in various fields, including physics, engineering, and economics. In this lecture, we will explore the theory and methods for solving such equations. We will discuss different types of first-order differential equations, including separable, exact, and linear equations, and their solution techniques. Additionally, we will delve into applications of these equations in modeling real-world phenomena such as population growth, heat transfer, and electrical circuits. By the end of this lecture, you will have a solid understanding of first-order differential equations and their applications.",
      9: "Higher order linear differential equations with constant coefficients and variable coefficients are an important area of study in mathematics and its applications. In this lecture, we will explore the theory and methods for solving such equations. We will discuss the characteristic equation method for constant coefficients and the method of variation of parameters for variable coefficients. Additionally, we will delve into applications of these equations in modeling real-world phenomena such as mechanical vibrations, electrical circuits, and heat transfer. By the end of this lecture, you will have a solid understanding of higher order linear differential equations and their applications.",
    },
  },
  {
    id: 3,
    name: "BEE & DE",
    code: "BEE",
    accent: "from-amber-500 to-orange-700",
    chapters: ["DC Circuits", "AC Circuits", "Logic Gates", "Latches and Flip-Flops"],
    playlists: {
      1: "PL81b_GzVmpj_hN39sNfcpzssXM4G7dDSj",
      2: "PL81b_GzVmpj_iPibA0J-aBNb-bitJHz2w",
      3: "PLgwJf8NK-2e6bxsyFDqkSjn9pDhk7J-q8",
      4: "PL81b_GzVmpj-OT81FF03ERn8ooCMVgycH",
    },
    descriptions: {
      0: "Basic Electrical Engineering (BEE) is a fundamental course that introduces students to the principles and applications of electrical engineering. The course covers a wide range of topics, including DC circuits, AC circuits, logic gates, latches and flip-flops, and communication systems. Through lectures, problem-solving sessions, and practical applications, students will gain a solid understanding of electrical engineering concepts and their relevance in various fields such as electronics, telecommunications, and power systems. By the end of this course, students will be equipped with the knowledge and skills necessary to analyze and design basic electrical circuits and systems.",
      1: "DC Circuits are fundamental to understanding the flow of electric current in a circuit. This lecture covers the basic components of DC circuits, including resistors, capacitors, and inductors, as well as Ohm's Law and Kirchhoff's Laws. Students will learn how to analyze simple DC circuits using techniques such as series and parallel combinations, voltage division, and current division. The lecture also includes numerical problems to reinforce the theoretical concepts and enhance problem-solving skills in DC circuit analysis.",
      2: "AC Circuits are essential for understanding the behavior of electric circuits that operate with alternating current. This lecture covers the fundamental concepts of AC circuits, including sinusoidal waveforms, phasors, impedance, and power in AC circuits. Students will learn how to analyze AC circuits using techniques such as phasor diagrams, complex impedance, and power factor correction. The lecture also includes numerical problems to reinforce the theoretical concepts and enhance problem-solving skills in AC circuit analysis.",
      3: "Logic Gates are the building blocks of digital circuits. This lecture covers the basic logic gates, including AND, OR, NOT, NAND, NOR, XOR, and XNOR gates. Students will learn how to analyze and design combinational logic circuits using these gates, as well as how to simplify logic expressions using Boolean algebra and Karnaugh maps. The lecture also includes numerical problems to reinforce the theoretical concepts and enhance problem-solving skills in digital logic design.",
      4: "Latches and Flip-Flops are fundamental components of sequential logic circuits. This lecture covers the basic types of latches and flip-flops, including SR latch, D latch, JK flip-flop, and T flip-flop. Students will learn how to analyze and design sequential logic circuits using these components, as well as how to create state diagrams and timing diagrams for sequential circuits. The lecture also includes numerical problems to reinforce the theoretical concepts and enhance problem-solving skills in sequential logic design.",
    },
  },
  {
    id: 4,
    name: "CEM",
    code: "CEM",
    accent: "from-teal-500 to-emerald-700",
    chapters: [
      "System of Forces",
      "Equilibrium of Rigid Bodies",
      "Friction",
      "Robot Kinematics (ICR)",
    ],
    playlists: {
      1: "PLT3bOBUU3L9jVJYwDCDE8FOJDvr0cU6U0",
      2: "PLT3bOBUU3L9gUQNXoRtPX-wW9QXq31c4r",
      3: "PLT3bOBUU3L9jJXGSFC_BQczz7nZpmcjO6",
      4: "PL81b_GzVmpj_f5oVMbGVzS757qTB94UDo",
    },
    descriptions: {
      0: "Computational Engineering Mechanics (CEM) is a multidisciplinary field that combines principles of engineering, mathematics, and computer science to analyze and solve complex problems in various engineering domains. It involves the use of computational methods and simulations to model and predict the behavior of physical systems, such as structures, fluids, and materials. CEM is widely used in industries such as aerospace, automotive, civil engineering, and manufacturing to optimize designs, improve performance, and reduce costs. By leveraging advanced algorithms and high-performance computing, CEM enables engineers to gain insights into the behavior of complex systems and make informed decisions in the design and analysis process.",
      1: "System of Forces is a fundamental concept in engineering mechanics that involves analyzing the forces acting on a body or structure. It encompasses the study of equilibrium, where the sum of forces and moments must equal zero for a system to be in a state of balance. This topic covers various types of forces, including gravitational, normal, frictional, and applied forces, as well as their interactions and effects on structures. Understanding the system of forces is crucial for designing safe and efficient structures, as it allows engineers to predict how a structure will respond to different loading conditions and ensure its stability and integrity.",
      2: "Equilibrium of Rigid Bodies is a fundamental topic in engineering mechanics that focuses on the conditions necessary for a rigid body to be in a state of equilibrium. It involves analyzing the forces and moments acting on a body and ensuring that they balance each other out. This topic covers concepts such as free-body diagrams, the principles of statics, and the application of equilibrium equations to solve for unknown forces and moments. Understanding the equilibrium of rigid bodies is essential for designing structures and mechanical systems that can withstand various loading conditions without collapsing or experiencing excessive deformation.",
      3: "Friction is a force that opposes the relative motion or tendency of motion between two surfaces in contact. It plays a crucial role in engineering mechanics, as it affects the behavior of structures and mechanical systems. This topic covers different types of friction, including static friction, kinetic friction, and rolling friction, as well as their characteristics and applications. Understanding friction is essential for designing systems that can effectively manage and utilize this force, such as brakes, clutches, and tires, to ensure safety and performance in various engineering applications.",
      4: "Kinematics of Rigid Bodies is a fundamental topic in engineering mechanics that focuses on the motion of rigid bodies without considering the forces that cause the motion. It involves analyzing the position, velocity, and acceleration of rigid bodies in two or three-dimensional space. This topic covers concepts such as relative motion, angular velocity, and the use of coordinate systems to describe the motion of rigid bodies. Understanding kinematics is essential for designing and analyzing mechanical systems, as it allows engineers to predict how a body will move under various conditions and ensure its proper functioning in applications such as robotics, vehicle dynamics, and machinery design.",
    },
  },
  {
    id: 5,
    name: "Chemistry",
    code: "CHEM",
    accent: "from-rose-500 to-pink-700",
    chapters: [
      "Spectroscopic Techniques and Applications",
      "Green Chemistry",
      "Polymers",
      "Fuels and Combustion",
      "Phase Rule and Applications",
      "Water Technology",
    ],
    playlists: {
      1: "PLiYAH68F-CTBTtumVFNH8exEvjWtUYdw_",
      2: "PLLf6O8XdGj03fkukqcW7HOTSK8u_up7nJ",
      3: "PLHWPZcIu1IxAvwCMNUukY5b0jJlNkxbw-",
      4: "PLLf6O8XdGj00RTPIi8Gn0zXuaaZvcUDj4",
      5: "PLLf6O8XdGj01keitLZ0scBnH80-MnNdu4",
      6: "PLT3bOBUU3L9j-0wblhAeSTODcI_uQNL5R",
    },
    descriptions: {
      0: "Chemistry is the scientific study of the properties and behavior of matter. It is a natural science that covers the elements that make up matter to the compounds composed of atoms, molecules and ions: their composition, structure, properties, behavior and the changes they undergo during a reaction with other substances.",
      1: "This lecture covers the fundamentals of optical fibres, including their structure, working principle, and applications. It also delves into the concept of numerical aperture, which is crucial for understanding light propagation in fibres. The lecture includes problem-solving sessions on numerical aperture, acceptance angle, V-number, modes of propagation, and the differences between step index and graded index fibres. By the end of this lecture, students will have a solid understanding of optical fibres and their significance in modern communication systems.",
      2: "This lecture provides an introduction to quantum mechanics, covering key concepts such as wave-particle duality, the uncertainty principle, and the time-dependent and time-independent Schrödinger equations. It also explores phase and group velocity, which are essential for understanding wave propagation in quantum systems. The lecture includes numerical problems to reinforce the theoretical concepts and enhance problem-solving skills in quantum mechanics.",
      3: "This lecture explores the phenomena of interference and diffraction, which are fundamental to understanding wave behavior. It covers the principles of superposition, constructive and destructive interference, and the conditions for observing interference patterns. The lecture also delves into diffraction, including single-slit and double-slit diffraction, as well as diffraction gratings. By the end of this lecture, students will have a comprehensive understanding of how waves interact and the resulting patterns that emerge.",
      4: "This lecture focuses on sensors, which are devices that detect and respond to changes in the environment. It covers various types of sensors, including temperature sensors, pressure sensors, and optical sensors. The lecture also explores the principles of sensor operation, signal processing, and applications in different fields such as healthcare, automotive, and industrial automation. By the end of this lecture, students will have a solid understanding of sensor technology and its significance in modern society.",
      5: "This lecture provides an overview of lasers, covering their principles of operation, types, and applications. It explores the concept of stimulated emission, population inversion, and the different components of a laser system. The lecture also delves into various types of lasers, including solid-state lasers, gas lasers, and semiconductor lasers. By the end of this lecture, students will have a comprehensive understanding of laser technology and its wide-ranging applications in fields such as medicine, communication, and manufacturing.",
      6: "This lecture covers the fundamentals of electrodynamics, which is the study of electric and magnetic fields and their interactions with charged particles. It explores Maxwell's equations, which describe how electric and magnetic fields are generated and altered by charges and currents. The lecture also delves into electromagnetic waves, their propagation, and applications in communication systems. By the end of this lecture, students will have a solid understanding of electrodynamics and its significance in modern physics and engineering.",
    },
  },
  {
    id: 6,
    name: "C Programming",
    code: "C",
    accent: "from-cyan-500 to-sky-700",
    chapters: [
      "C Programming (Pradeep Giri)",
      "C Programming (Apna College 10hr One Shot)",
    ],
    playlists: {
      1: "PL81b_GzVmpj_NAkGX3t3mlx8eZlL4fwdI",
      2: "PL81b_GzVmpj_Mt7kfr9oI3IV0po8LQBOK",
    },
    descriptions: {
      0: "C Programming is a general-purpose, procedural programming language supporting structured programming and lexical variable scope.",
      1: "C Language is a powerful programming language that provides a solid foundation for understanding programming concepts. This lecture covers the basics of C, including its history, features, and applications. It also introduces the structure of a C program, the compilation process, and how to write and run a simple C program. By the end of this lecture, students will have a clear understanding of what C programming is and how to get started with it.",
      2: "C Language is a powerful programming language that provides a solid foundation for understanding programming concepts. This lecture covers the basics of C, including its history, features, and applications. It also introduces the structure of a C program, the compilation process, and how to write and run a simple C program. By the end of this lecture, students will have a clear understanding of what C programming is and how to get started with it.",
    },
  },
  {
    id: 7,
    name: "OOP Using Java",
    code: "JAVA",
    accent: "from-orange-500 to-red-700",
    chapters: [
      "OOP using Java (Kunal Kushwaha)",
      "Java and DSA with Java (Apna College)",
    ],
    playlists: {
      1: "PL9gnSGHSqcno1G3XjUbwzXHL8_EttOuKk",
      2: "PLfqMhTWNBTe3LtFWcvwpqTkUSlB32kJop",
    },
    descriptions: {
      0: "Java is a versatile and widely-used programming language that is known for its platform independence, object-oriented programming capabilities, and extensive libraries. It is used for developing a wide range of applications, from web and mobile applications to enterprise software and games. Java's \"write once, run anywhere\" philosophy allows developers to create applications that can run on any device with a Java Virtual Machine (JVM). With its robust security features, scalability, and strong community support, Java continues to be a popular choice for developers around the world.",
      1: "Object Oriented Programming (OOP) is a programming paradigm that uses \"objects\" to design applications and computer programs. It utilizes several key principles, including encapsulation, inheritance, polymorphism, and abstraction. OOP allows developers to create modular, reusable code by organizing data and behavior into objects. This approach promotes code maintainability and scalability, making it easier to manage complex software systems. In Java, OOP is a fundamental concept that enables developers to create classes and objects to model real-world entities and their interactions effectively.",
      2: "DSA with Java refers to the implementation of Data Structures and Algorithms using the Java programming language. Data Structures are ways of organizing and storing data to enable efficient access and modification, while Algorithms are step-by-step procedures for solving problems. Java provides a rich set of built-in data structures such as arrays, linked lists, stacks, queues, trees, and graphs, along with powerful libraries like the Collections Framework. Learning DSA with Java helps developers understand how to optimize code for performance and solve complex problems effectively, making it an essential skill for software development and competitive programming.",
    },
  },
];

export const getSubjectById = (id) => SUBJECTS.find((s) => s.id === id);
